### ISSUE TITLE
Exception occured during evaluation of API byg

### ISSUE THREAD

**Issue by TeslaP09** [Crendgrim/DynamicCrosshairCompat#19]
Hey there, the mod just keeps spamming my log with this... Here is my log file: [latest.log](https://github.com/Crendgrim/DynamicCrosshairCompat/files/11886514/latest.log)

[Render thread/ERROR]: Exception occurred during evaluation of API byg
java.lang.NoClassDefFoundError: potionstudios/byg/common/block/end/TheriumCrystalBlock
	at mod.crend.dynamiccrosshair.compat.byg.ApiImplOhTheBiomesYoullGo.computeFromBlock(ApiImplOhTheBiomesYoullGo.java:71) ~[dynamiccrosshair-compat-3.3.2+1.19.2.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:102) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:116) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:313) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:353) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:374) [dynamiccrosshair-5.6.2+1.19.2-fabric.jar:?]
	at net.minecraft.class_329.handler$fbn000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:32041) [client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1305) [client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1271) [client-intermediary.jar:?]
	at net.minecraft.class_310.redirect$hfn000$g4mespeed$onTickRedirectInteractionManagerTick(class_310.java:26579) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1792) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1135) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
Caused by: java.lang.ClassNotFoundException: potionstudios.byg.common.block.end.TheriumCrystalBlock
	... 19 more

**Comment by Crendgrim** [comment]
Ah, BYG finally marked their update as stable. Will update the compat, thank you for the report!

**Comment by Crendgrim** [comment]
Pushed version 3.3.3 that might not have fully correct crosshairs everywhere but shouldn't fail evaluating the API anymore. Do let me know if you encounter any blocks or items that you feel should have other crosshairs.
