### ISSUE TITLE
guard villager compat seems broken

### ISSUE THREAD

**Issue by SettingDust** [Crendgrim/DynamicCrosshairCompat#25]
1.20.1 fabric
```
[19:33:47] [Render thread/ERROR] (dynamiccrosshair) Exception occurred during evaluation of API guardvillagers
java.lang.NoClassDefFoundError: dev/mrsterner/guardvillagers/common/entity/GuardEntity
	at mod.crend.dynamiccrosshair.compat.guardvillagers.ApiImplGuardVillagers.computeFromEntity(ApiImplGuardVillagers.java:37) ~[dynamiccrosshair-compat-3.4+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:89) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:127) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:207) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:315) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:363) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:384) ~[dynamiccrosshair-7.3+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$emo000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:26905) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.23.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.23.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:127) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: dev.mrsterner.guardvillagers.common.entity.GuardEntity
	... 20 more
```

**Comment by Crendgrim** [comment]
Thank you for the report! Should be updated to the new version of GuardVillagers now.
