### ISSUE TITLE
Issue with Dramatic Doors

### ISSUE THREAD

**Issue by Numerosityy** [Crendgrim/DynamicCrosshairCompat#27]
Error message: 
`[17/11/2023 17:57:19 PM] [Render thread/ERROR] Exception occurred during evaluation of API dramaticdoors
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.compat.dramaticdoors.ApiImplDramaticDoors.computeFromBlock(ApiImplDramaticDoors.java:30)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:103)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:117)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:207)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:315)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:363)
[17/11/2023 17:57:19 PM] 	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:384)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_329.handler$dph000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:2403)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_329.method_1748(class_329.java:1195)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_329.method_39191(class_329.java:1159)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_310.method_1574(class_310.java:1846)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_310.method_1523(class_310.java:1181)
[17/11/2023 17:57:19 PM] 	at net.minecraft.class_310.method_1514(class_310.java:802)
[17/11/2023 17:57:19 PM] 	at net.minecraft.client.main.Main.main(Main.java:250)
[17/11/2023 17:57:19 PM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[17/11/2023 17:57:19 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[17/11/2023 17:57:19 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[17/11/2023 17:57:19 PM] Caused by: java.lang.ClassNotFoundException: com.fizzware.dramaticdoors.blocks.ShortNetheriteDoorBlock`

**Comment by Crendgrim** [comment]
Fixed in 3.6, thank you for the report!
