### ISSUE TITLE
Better Combat support

### ISSUE THREAD

**Issue by Geonaut3** [Crendgrim/DynamicCrosshairCompat#3]
Better Combat's modified weapon attack range is not taken into account by Dynamic Crosshair's "looking at entity" behavior, and uses the vanilla attack range. Dynamic Crosshair should instead use the hitbox of the current weapon being used/swung to modify the crosshair.

[https://modrinth.com/mod/better-combat](https://modrinth.com/mod/better-combat)

**Comment by Crendgrim** [comment]
I have looked into this some. It looks like Better Combat uses a different way to select for hittable entities. DynamicCrosshair is architectured heavily around the vanilla crosshair target selector. This will require some deep changes to facilitate compatibility.

Notes for myself, mostly:
- Better Combat has an option to recolour the crosshair when hittable targets are in range. This should be supported; DC somehow needs to gain a way to hook into this.
- It seems like all weapons have a range of 2.5, which is just about shorter than vanilla's range. It also appears as though hitbox calculations are done somewhere in the mod logic; and `MinecraftClientExtension.hasTargetsInRange()` might be sufficient to query if we ignore further special weapon-entity-interactions. I am not aware of any situation in modded or vanilla that has these, so that should be fine. Hopefully.

My thought is that even just adding the colour would already help a lot. And probably be *much* easier than fully supporting weapon ranges. Still will require some rework to add the required hooks.

**Comment by Crendgrim** [comment]
I thought about it some more and realised a simple raycast only when necessary will not have a big performance impact. Thus, longer ranges are also fully supported now. The only thing it doesn't do is check for entities within the sweep range; unsure how this works in all corner cases. I believe that makes the compatibility very intuitive, so I consider this complete. Feel free to reopen if you find any weird cases.

**Comment by antgly** [comment]
As of the latest release of Better Combat (two days ago), a crash happens when trying to swing at a fish with a sword. The method dealing with handling entities seems to be out of date (the method `hasTargetsInRange ` is now `hasTargetsInReach`):

```
Time: 2022-11-25 19:01:13
Description: Unexpected error
 
java.lang.NoSuchMethodError: 'boolean net.bettercombat.api.MinecraftClient_BetterCombat.hasTargetsInRange()'
	at mod.crend.dynamiccrosshair.compat.bettercombat.ApiImplBetterCombat.checkEntity(ApiImplBetterCombat.java:48)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkHandOnEntity(CrosshairHandler.java:46)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkHandsOnEntity(CrosshairHandler.java:51)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:202)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:262)
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:283)
	at net.minecraft.class_329.handler$zzc000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:7542)
	at net.minecraft.class_329.method_1748(class_329.java:1305)
	at net.minecraft.class_329.method_39191(class_329.java:1271)
	at net.minecraft.class_310.method_1574(class_310.java:1792)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

```

**Comment by Crendgrim** [comment]
Thanks, pushed version 1.11.3 to fix this :)
