### ISSUE TITLE
[Bug]: Compat Meadow - ChairBlock NoClassDefFoundError - Fabric 1.20.1

### ISSUE THREAD

**Issue by xR4YM0ND** [Crendgrim/DynamicCrosshairCompat#33]
[latest.log](https://gist.github.com/xR4YM0ND/9aed4f7f8719518187e7acbe94e08458)

```js
[20:21:23] [Render thread/ERROR]: Exception occurred during evaluation of API meadow
java.lang.NoClassDefFoundError: juuxel/adorn/block/ChairBlock
	at mod.crend.dynamiccrosshair.compat.meadow.ApiImplMeadow.computeFromBlock(ApiImplMeadow.java:103) ~[dynamiccrosshair-compat-3.7.1+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvancedByHand(CrosshairHandler.java:104) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairAdvanced(CrosshairHandler.java:118) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:208) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.2+1.20-fabric.jar:?]
	at net.minecraft.class_329.handler$dcl000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:2404) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[client-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
Caused by: java.lang.ClassNotFoundException: juuxel.adorn.block.ChairBlock
	... 17 more
```

**Comment by Crendgrim** [comment]
I appreciate you reporting these when other mods update! I had some trouble with fixing the ExtendedDrawers bug you reported (short of removing the whole compat layer), but I will take some time tomorrow to look fixing into both.

**Comment by Crendgrim** [comment]
Ah, this one was just stupidity. Fixed!
