### ISSUE TITLE
[Update Compatibility]  API vinery

### ISSUE THREAD

**Issue by ninjaeon** [Crendgrim/DynamicCrosshairCompat#39]
Getting log spam regarding Let's Do:  Vinery

On Fabric 1.20.1 with:
dynamiccrosshair-7.4.4+1.20-fabric.jar
dynamiccrosshair-compat-3.7.3+1.20.1.jar

Currently using, but saw these errors on recent previous versions:
letsdo-vinery-fabric-1.4.16.jar
letsdo-API-fabric-1.2.10-fabric.jar

Full Log:  
https://mclo.gs/qfDz4NL

Relevant log parts:
```
[11:31:09] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[11:31:09] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:09] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:09] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:11] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:11] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:11] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.10.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: satisfyu.vinery.block.WineRackStorageBlock
	... 19 more
[11:31:11] [Render thread/ERROR]: Exception occurred during evaluation of API vinery
java.lang.NoClassDefFoundError: satisfyu/vinery/block/WineRackStorageBlock
	at mod.crend.dynamiccrosshair.compat.vinery.ApiImplVinery.isAlwaysInteractableBlock(ApiImplVinery.java:57) ~[dynamiccrosshair-compat-3.7.3+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.handler$ego000$dynamiccrosshair$tickDynamicCrosshair(InGameHud.java:1904) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.tick(InGameHud.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
```
	
...keeps going (see full log)

**Comment by Crendgrim** [comment]
Thank you for the report, updated!
