### ISSUE TITLE
mod bug in meadow mod compat

### ISSUE THREAD

**Issue by 8MiYile** [Crendgrim/DynamicCrosshairCompat#44]
[latest.log](https://github.com/user-attachments/files/16370360/latest.log)
> [!TIP]
minecraft 1.20.1
dynamiccrosshair 7.4.4+1.20
\\-- yaclx 1.12+1.20.2
dynamiccrosshaircompat 3.7.4+1.20.1
meadow 1.3.17

main error log
```log
[10:21:00] [Render thread/ERROR]: Exception occurred during evaluation of API meadow
java.lang.NoClassDefFoundError: net/satisfyu/meadow/item/WateringCanItem
	at mod.crend.dynamiccrosshair.compat.meadow.ApiImplMeadow.isUsableItem(ApiImplMeadow.java:221) ~[%5B动态准星兼容%5D%20dynamiccrosshair-compat-3.7.4+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.api.DynamicCrosshairApi.getItemCategory(DynamicCrosshairApi.java:145) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:141) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.class_329.handler$ejg000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:2904) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[Utopia%20journey3.2fix.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.satisfyu.meadow.item.WateringCanItem
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 23 more
[10:21:00] [Render thread/ERROR]: Exception occurred during evaluation of API meadow
java.lang.NoClassDefFoundError: net/satisfyu/meadow/block/CheeseFormBlock
	at mod.crend.dynamiccrosshair.compat.meadow.ApiImplMeadow.isAlwaysInteractableBlock(ApiImplMeadow.java:56) ~[%5B动态准星兼容%5D%20dynamiccrosshair-compat-3.7.4+1.20.1.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairSimple(CrosshairHandler.java:192) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshairDynamic(CrosshairHandler.java:206) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.buildCrosshair(CrosshairHandler.java:316) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.checkShowCrosshair(CrosshairHandler.java:364) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at mod.crend.dynamiccrosshair.component.CrosshairHandler.tick(CrosshairHandler.java:385) ~[%5B动态准星%5D%20dynamiccrosshair-7.4.4+1.20-fabric.jar:?]
	at net.minecraft.class_329.handler$ejg000$dynamiccrosshair$tickDynamicCrosshair(class_329.java:2904) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1748(class_329.java:1195) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_39191(class_329.java:1159) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1846) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[Utopia%20journey3.2fix.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.satisfyu.meadow.block.CheeseFormBlock
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 22 more
```

**Comment by Crendgrim** [comment]
Should be updated, thank you for the report. I did remove some rules & did not implement new ones, though.
