### ISSUE TITLE
Incompatibility with Ironchests

### ISSUE THREAD

**Issue by URSFR** [Crendgrim/DynamicCrosshairCompat#7]
When I put a copper chest in my hand, the game crashed.

Crash log:

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'dynamiccrosshair'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'dynamiccrosshair' provided by 'dynamiccrosshaircompat'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at mod.crend.dynamiccrosshair.DynamicCrosshair.lambda$onInitializeClient$0(DynamicCrosshair.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at mod.crend.dynamiccrosshair.DynamicCrosshair.onInitializeClient(DynamicCrosshair.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: mod.crend.dynamiccrosshair.compat.ironchests.ApiImplIronChestsRestocked
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 12 more
Caused by: java.lang.ClassNotFoundException: mod.crend.dynamiccrosshair.compat.ironchests.ApiImplIronChestsRestocked
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	... 14 more

**Comment by Crendgrim** [comment]
Oh, this is a weird bug. It took me a while to figure this out. There's two mods on CurseForge, "Iron Chests (Fabric)" and "Iron Chests: Restocked". Both of them use the identifier "ironchests". I will have to figure out how to handle that properly..

**Comment by Crendgrim** [comment]
The solution is a bit ugly, but the situation is as well. This should work properly with both mods from DynamicCrosshairCompat 1.10 on.
